htk_instructions=function(){

  cat("------------------------------------------------------------\n")
  cat("# INSTRUCTION TO USE THE PACKAGE OECDHousingToolkit \n")
  cat("------------------------------------------------------------\n\n")

  cat("This package provides a Rmardown template and a style sheet to create an html")
  cat(" with the standards of OECD that will guarantee an uniform structure of each chapter of the toolkit:\n")
  cat("To access the template (and assuming that if you read those line you have installed and loaded the package")
  cat("in a rstudio session) follow the following steps\n \n")

  cat("# Accessing the template\n")
  cat("------------------------------------------------------------\n\n")

  cat("  1. click on 'file'in the top left corner of the Rstudio window \n")
  cat("  2. click on 'new file' and 'R markdown'\n")
  cat("  3. A window will pop up and on the side bar select 'from template'\n")
  cat("  4. Select the template 'housing_toolkit_chapter', provide a name for the chapter (myname) and a location in your disk\n")
  cat("  5. This will open a script 'myname.Rmd' that will be located in a folder containing two files: the .Rmd file where")
  cat(" you will write the content and a OECDstyle.css file that you do not have to edit that contains the style that will")
  cat(" be applied to the document when transformed into html.\n \n")
  cat("  6. Generate the html document by clicking on the button 'knit' and preview the template\n")

  cat("At that stage you have everything to start editing your own chapter.\n \n")

  cat("To have more details about the Rmardown syntax and capabilities please refers to Rmardown documentation\n")
  cat("- https://rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf\n")
  cat("- https://bookdown.org/yihui/rmarkdown/ \n")
  cat("- https://www.fun-mooc.fr/c4x/UPSUD/42001S02/asset/RMarkdown.html \n\n")

  cat("# Editing your chapter\n")
  cat("------------------------------------------------------------\n\n")

  cat("The template is structured as following: 6 main sections\n\n")
  cat("Context\n")
  cat("\t - With one paragraph of general introduction\n")
  cat("\t - One explanatory diagram\n")
  cat("\t - Definitions of the main concepts of the chapter\n\n")
  cat("Outcomes\n")
  cat("\t - as many subsections as relevant economic outcome with a paragraph of explanation and a figure\n\n")
  cat("Policies\n")
  cat("\t - as many subsections as relevant policy discussions with for each an introductory paragraph with ")
  cat(" the key message and a collapsible chunk containing more details: with a subsection 'Policy description and")
  cat(" rationale' and another 'Impact of policies'\n\n")
  cat("Definitions\n")
  cat("\t - Glossary of the indicators used")
  cat("Data source\n")
  cat("\t - Additional sources of data and possibly a link to download the underlying data\n")
  cat("References and further readings\n")
  cat("\t - Papers and relevant documentation\n\n")

  cat("\n One of the main functionality of Rmarkdown is to be able to combine text and data\n")
  cat("The template contains example for three type of plots that are available with the following functions\n")
  cat("- htk_scatterplot()\n")
  cat("- htk_lineplot()\n")
  cat("- htk_barplot()\n")
  cat("If you want to include more figures just copy and paste the chunk of code and adjust to what you want\n")
  cat("To create a new chunk of code click on the button insert at the top right and select R.\n")
  cat("Inside the chunk you can use standard R code and manipulate the data as you wish.\n")
  cat("Please refer to the documentation for more details. For further help contact:\n")
  cat("boris.cournede@oecd.org, maxime.nguyen@oecd.org or manuel.betin@oecd.org\n\n")

  cat("Good luck\n\n")

  cat("NB: a few programing tips from Tim Peters, The Zen of Python\n")
  cat("- Beautiful is better than ugly.\n")
  cat("- Explicit is better than implicit.\n")
  cat("- Simple is better than complex.\n")
  cat("- Complex is better than complicated.\n")
  cat("- Flat is better than nested.\n")
  cat("- Sparse is better than dense.\n")
  cat("- Readability counts.\n")
  cat("- Special cases aren't special enough to break the rules.\n")
  cat("- Although practicality beats purity.\n")
  cat("- Errors should never pass silently.\n")
  cat("- Unless explicitly silenced.\n")
  cat("- In the face of ambiguity, refuse the temptation to guess.\n")
  cat("- There should be one (and preferably only one obvious) way to do it.\n")
  cat("- Although that way may not be obvious at first unless you are Dutch.\n")
  cat("- Now is better than never\n")
  cat("- Although never is often better than right now.\n")
  cat("- If the implementation is hard to explain, it's a bad idea.\n")
  cat("- If the implementation is easy to explain, it may be a good idea.\n")
  cat("- Namespaces are one honking great idea -- let's do more of those!\n")

}

htk_instructions()
